### ISSUE TITLE
Bad renders after last ControlNet update --

### ISSUE THREAD

**Issue by makeoo1** [lllyasviel/ControlNet#255] opened 2023-03-10 14:11 UTC
i have been using controlnet since a while without any problem. After recently updating all i am getting is "half-renders", like if SD was not completing the steps. I tested it with all the controlnet model but the result is the same

I haven't touched anything in the models folder, just added the new models to the one i already had and always worked.

I am just guessing but I think it has to do with **yaml file**. Problem is that i am also not sure which yaml file could be casuing the problem, since there a few. 

![1111 img2img](https://user-images.githubusercontent.com/113861865/224335501-066493b4-b74f-4a89-9208-e2f3e10a1ae7.png)
![1111 models](https://user-images.githubusercontent.com/113861865/224335506-c6cc43aa-d784-4bfb-9685-651d6a47c003.png)
![11111 conmtrol](https://user-images.githubusercontent.com/113861865/224335509-24130dbd-fe30-440b-b031-e14da5913c27.png)

Any help would be very appreciated. Thx a lot!

**Comment by wcarletsdrive** [comment] 2023-03-10 16:42
![03578501-CF7C-4CF7-8DF1-670719E580D3](https://user-images.githubusercontent.com/110745584/224372750-bac44e91-7c5e-4b80-9e39-831266d977dd.png)

I am getting horrible renders too and I did a fresh install of stable diffusion webui as a friend instructed me, only changed controlnet model cache size to 2 and added an extra controlnet slot and I have this type of quality no matter what. I even followed this tutorial exactly the same and mine looks awful.. What the hell😔 I need a solution ASAP for this extension because I need to use it😔 https://youtu.be/wDM8iDK-yng

**Comment by lllyasviel** [comment] 2023-03-10 18:47
ok let us look into it

**Comment by wcarletsdrive** [comment] 2023-03-10 18:48
Thank you for looking into it

**Comment by lllyasviel** [comment] 2023-03-10 18:51
can you check your setting and see if you mistakenly checked "cfg-based controlnet"?

**Comment by wcarletsdrive** [comment] 2023-03-10 18:56
When I reinstalled webui for the fresh install, that setting was off. The only setting checked in controlnet is use mid-control on highres pass. My other install of webui previously before the fresh install is in this picture below. Either way I get bad looking renders that don't represent the style at all. Even if I am using canny or depth mode
![settings](https://user-images.githubusercontent.com/110745584/224402580-591439d9-c487-43c3-943c-19f225222fce.PNG)
l, it all looks horrible

**Comment by lllyasviel** [comment] 2023-03-10 18:58
1. uncheck the cfg-based  guidance and restart your webui completely, is the problem solved?
2. does this option checked by default when fresh install?

**Comment by wcarletsdrive** [comment] 2023-03-10 19:00
1. No, and I used this on the previous install of webui
2. On the fresh install of webui, this isn't checked and I still get the same bad quality

**Comment by lllyasviel** [comment] 2023-03-10 19:01
it seems that the "cfg-based guidance" is broken. we will further look into it

**Comment by wcarletsdrive** [comment] 2023-03-10 19:03
Thank you so much once again 🙏

**Comment by lllyasviel** [comment] 2023-03-10 19:08
are u willing to share the input image that you tested?

**Comment by makeoo1** [comment] 2023-03-10 19:11
here's mine


![img000](https://user-images.githubusercontent.com/113861865/224405120-7f8028a3-082f-456c-b590-085aa2eba9ed.png)

**Comment by makeoo1** [comment] 2023-03-10 19:12
i just saw the updates of the issue. 

I also followed your instruction but the problem stays

**Comment by wcarletsdrive** [comment] 2023-03-10 19:15
![appatnfphiaa1](https://user-images.githubusercontent.com/110745584/224405685-aea433c4-a3c9-46c2-add0-63a9b4a66c07.jpg)

Second image is for the style
![33](https://user-images.githubusercontent.com/110745584/224405860-1ca5b669-cb61-4188-9583-3717f8949d67.png)

I also tried using an image that wasn't at 512 x 512, used innerfit in controlnet too.

**Comment by lllyasviel** [comment] 2023-03-10 19:24
it seems that the building image is a difficult case for ControlNet and the model fail to recognize it. it is not a bug.
The girl case is likely to be caused by t2i adaper, which is not a part of ControlNet. let me know if you can reproduce the problem without using t2i adaper

**Comment by wcarletsdrive** [comment] 2023-03-10 19:25
![00000-3875445158](https://user-images.githubusercontent.com/110745584/224407492-7f8e7ad9-cdaf-4061-8aca-da1c08666b45.png)
![00001-2139376770](https://user-images.githubusercontent.com/110745584/224407499-3017c6c6-5df8-4a21-b62a-21f723d13960.png)

Sadly on looks I am getting and I got the style adapter from here https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models 

The canny, and depth models etc are from your huggingface

**Comment by lllyasviel** [comment] 2023-03-10 19:26
![image](https://user-images.githubusercontent.com/19834515/224407892-b53a7d1b-da77-4734-85a7-4d11adc9f53a.png)
Can you get similar quality in webui?

**Comment by lllyasviel** [comment] 2023-03-10 19:30
![image](https://user-images.githubusercontent.com/19834515/224409650-1e0098ac-7be8-41a6-8c3b-c6bea7d29551.png)
can you send me your screenshot with exactly same setting with me?

**Comment by lllyasviel** [comment] 2023-03-10 19:32
For the girl image case, please let me know if the problem exist without using t2i adapter. If the problem exist with pure text prompts, we will look into it deeper.

**Comment by wcarletsdrive** [comment] 2023-03-10 19:36
All below are with having the weight in controlnet range from 0.5-1. Also, using your models instead and no adapter. If I have the weight low like 0.15, of course I see my prompt but this defeats the point of me using your extension :(

![weird](https://user-images.githubusercontent.com/110745584/224410824-f364e942-e995-46b1-9cec-65117d2dc39c.PNG)
![00005-4028782195](https://user-images.githubusercontent.com/110745584/224410933-3ca8cb5c-76d6-454f-bcb4-94f9e4237c6f.png)
![00006-518631049](https://user-images.githubusercontent.com/110745584/224410937-15541270-1c59-4651-8b4b-a493e6d6eeb2.png)
![00008-2963964337](https://user-images.githubusercontent.com/110745584/224411257-254899a7-b41d-41b0-817e-702ab2e66968.png)
![00009-3115818428](https://user-images.githubusercontent.com/110745584/224411260-7e41aa46-a82f-466b-8af6-760ec20c8680.png)

**Comment by lllyasviel** [comment] 2023-03-10 19:42
From the result it seems that the model works as intended. If no additional bugs are reported (especially thay building image), we will close this soon.
The t2i-adapter is from a 3rd team (Tencent-ARC), and the webui plugin's support for t2i-adapter is experimental - because we are not sure if that model is robust enough for a production environment. 
All standard controlnets are well-tested and should be robust.

If you want to transfer the prompt contents into your wanted coarse shape, a better choice could be using the depth model and tune the parameters a bit.

Thank you for your supports as always.

**Comment by wcarletsdrive** [comment] 2023-03-10 19:47
Well I appreciate you taking the time looking into this for us at least, thank you for trying, I really wish this would be totally different. But before you go just to make sure, I am doing everything correctly on my end?

**Comment by lllyasviel** [comment] 2023-03-10 19:48
Besides, you are encouraged to direct your issue to Tencent-ARC 
https://github.com/TencentARC/T2I-Adapter
Nevertheless, please note that they are an independent team and may not have the same way as us to interact with end users.

**Comment by lllyasviel** [comment] 2023-03-10 19:53
I closed the bug issue in webui https://github.com/Mikubill/sd-webui-controlnet/issues/555
let me know if the problem still exist with that building image and I will reopen it

**Comment by lllyasviel** [comment] 2023-03-10 19:58
And before you report to Tencent-ARC you are encouraged to see if your problem can be reproduced by their official demo https://huggingface.co/spaces/Adapter/T2I-Adapter

**Comment by wcarletsdrive** [comment] 2023-03-10 20:01
Thanks for that recommendation. I tried it just now and used a different input image and the issue still proceeds so there is something going on. Its weird because this is a fresh install of webui. SMH..

**Comment by lllyasviel** [comment] 2023-03-10 20:03
![image](https://user-images.githubusercontent.com/19834515/224416786-532ba81a-4684-4a01-91e1-53b34195bdb8.png)
Unfortunately, this is because that model is not robust enough. The problem even exist in their official demos.
We are not able to do anything more about this. This model belongs to Tencent-ARC

**Comment by wcarletsdrive** [comment] 2023-03-10 20:06
Thank God it isn't just me, THAT is good news, so within the two days of people making videos about this tool, something got broken. I reached out to them, and even though this will be closed, can I still send them this thread so they have deeper info and more proof of what I am dealing with?

**Comment by lllyasviel** [comment] 2023-03-10 20:07
I am going to close this issue. feel free to let me know if real addional bugs are reported and I will reopen it.

**Closed by lllyasviel** 2023-03-10 20:07 UTC

**Comment by lllyasviel** [comment] 2023-03-10 20:08
> Thank God it isn't just me, THAT is good news, so within the two days of people making videos about this tool, something got broken. I reached out to them, and even though this will be closed, can I still send them this thread so they have deeper info and more proof of what I am dealing with?

Again, any problem caused by other projects should be directly posted to that project, like https://github.com/TencentARC/T2I-Adapter/issues

**Comment by makeoo1** [comment] 2023-03-10 21:05
so followed your settings and it seems like its working now for me. I will test it with more random settings and prompt and let you know how is it going
![11111samesetrt](https://user-images.githubusercontent.com/113861865/224427990-e4113206-3abe-4ad5-9d3b-3a1ffee05cc6.png)

**Comment by makeoo1** [comment] 2023-03-10 22:46
For me everything seems fixed. Thank you guys!
